# Generated by Django 3.2.7 on 2021-09-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20210911_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
